#!/usr/bin/env python3
"""Export thesis tables from frozen public aggregates; never open raw predictions.

Run from any directory. --check compares outputs without writing. Bootstrap CIs
are copied from the frozen aggregate and hash-bound, not reconstructed from
aggregate counts: the cross-seed joint question outcomes are intentionally absent.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import io
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = Path(__file__).resolve().parent
RESULTS = "results/agent_feedback/"
FILES = {
    "holdout": "holdout_v1_analysis.json",
    "summary": "holdout_v1_summary.json",
    "audit": "holdout_v1_execution_audit.json",
    "protocol": "protocol_holdout_v1.json",
    "decision": "holdout_stage_decision_v1.json",
    "split": "split_manifest.json",
    "pairs": "recovery_pairs.json",
    "corpus": "continuation_data.json",
    "token_audit": "continuation_token_audit.json",
    "dev1": "recovery_vs_clean_dev.json",
    "dev2": "recovery_vs_clean_dev_seed20261004.json",
    "rl": "rl_stage_decision_v1.json",
    "rl_summary": "rl_paired_v1_summary.json",
    "feedback": "feedback_diagnostic_decision_v1.json",
    "initial_input": "initial_sft_v1/input_manifest.json",
    "program_input": "program_sft_v1/input_manifest.json",
    "clean_input": "clean_sft_v1/input_manifest.json",
    "recovery_input": "recovery_sft_v1/input_manifest.json",
    "clean_seed2_input": "clean_sft_seed20261004/input_manifest.json",
    "recovery_seed2_input": "recovery_sft_seed20261004/input_manifest.json",
}
CODE = ["recovery.py", "continuation_data.py", "training_data.py", "train_sft.py",
        "environment.py", "inference.py", "compare.py", "holdout_analysis.py",
        "holdout_runs.py", "feedback_mask.py"]


def digest(artifact):
    return hashlib.sha256(artifact.read_bytes()).hexdigest()


def close(left, right):
    if not math.isclose(left, right, rel_tol=1e-10, abs_tol=1e-10):
        raise ValueError(f"Aggregate arithmetic differs: {left} != {right}")


def build():
    docs = {key: json.loads((ROOT / RESULTS / name).read_text()) for key, name in FILES.items()}
    report, summary, audit = (docs[key] for key in ("holdout", "summary", "audit"))
    for key, field in [("holdout", "analysis_sha256"), ("audit", "execution_audit_sha256"),
                       ("protocol", "protocol_sha256")]:
        if digest(ROOT / RESULTS / FILES[key]) != summary[field]:
            raise ValueError(f"Frozen summary binding changed: {key}")
    if summary["status"] != "completed" or not audit["audit_passed"] or audit["mismatch_count"]:
        raise ValueError("Holdout is not completed and replay verified")
    if sum(x["trajectories"] for x in audit["models"].values()) != 10000:
        raise ValueError("Unexpected replay coverage")
    # Also retain existing source/code bindings from construction artifacts.
    for key in ("corpus",):
        for item in docs[key]["sources"].values():
            candidate = ROOT / item["path"]
            if candidate.is_file() and candidate.suffix != ".jsonl":
                if digest(candidate) != item["sha256"]:
                    raise ValueError(f"Construction binding differs: {item['path']}")

    rows, tex = [], ["% Generated by export_evidence.py; do not edit tables by hand."]

    def row(table, label, metric, value, unit, source, pointer, derivation="copied"):
        rows.append(dict(table=table, label=label, metric=metric, value=value, unit=unit,
                         source=RESULTS + FILES[source], json_pointer=pointer, derivation=derivation))

    def table(command, headers, data, columns):
        tex.extend(["\\newcommand{\\" + command + "}{%", "\\begin{tabular}{" + columns + "}",
                    "\\toprule", " & ".join(headers) + r" \\", "\\midrule"])
        tex.extend(" & ".join(map(str, record)) + r" \\" for record in data)
        tex.extend(["\\bottomrule", "\\end{tabular}%", "}"])

    holdout_table, cost_table = [], []
    labels = {"P": "P", "A_20261003": "$A_1$", "C_20261003": "$C_1$",
              "A_20261004": "$A_2$", "C_20261004": "$C_2$"}
    for arm, metrics in report["arms"].items():
        n = metrics["questions"]
        close(metrics["accuracy"], metrics["correct"] / n)
        close(metrics["finished"] + metrics["failed_to_finish"], n)
        close(metrics["totals"]["total_tokens"], metrics["totals"]["input_tokens"] + metrics["totals"]["generated_tokens"])
        for metric in ["questions", "correct", "accuracy", "finished", "failed_to_finish"]:
            row("holdout", arm, metric, metrics[metric], "fraction" if metric == "accuracy" else "count",
                "holdout", f"/arms/{arm}/{metric}")
        for metric, value in metrics["totals"].items():
            row("holdout_cost", arm, metric, value, "count", "holdout", f"/arms/{arm}/totals/{metric}")
        holdout_table.append([labels[arm], metrics["correct"], f"{100 * metrics['accuracy']:.2f}",
                              metrics["finished"], metrics["failed_to_finish"]])
        cost_table.append([labels[arm], metrics["totals"]["calls"], metrics["totals"]["invalid_calls"],
                           f"{metrics['totals']['input_tokens']:,}", f"{metrics['totals']['generated_tokens']:,}",
                           f"{metrics['totals']['total_tokens']:,}"])
    table("PublicHoldoutTable", ["模型", "正确数", r"准确率（\%）", "完成数", "未完成数"], holdout_table, "lrrrr")
    table("PublicCostTable", ["模型", "调用数", "无效调用", "输入 token", "生成 token", "总 token"], cost_table, "lrrrrr")

    paired_table = []
    for name, comparison in report["paired_comparisons"].items():
        a, c = (comparison["arms"][k] for k in ("baseline", "candidate"))
        outcomes = comparison["paired_outcomes"]
        close(outcomes["corrected"] - outcomes["regressed"], c["correct"] - a["correct"])
        close(sum(outcomes[k] for k in ["corrected", "regressed", "both_correct", "both_wrong"]), comparison["questions"])
        close(comparison["accuracy_delta_pp"], 100 * (c["correct"] - a["correct"]) / comparison["questions"])
        row("holdout_paired", name, "delta_pp", comparison["accuracy_delta_pp"], "pp", "holdout", f"/paired_comparisons/{name}/accuracy_delta_pp")
        ci = comparison["statistical_evidence"]["accuracy_delta_pp_ci"]
        for index, bound in enumerate(ci):
            row("holdout_paired", name, ["ci_low", "ci_high"][index], bound, "pp", "holdout",
                f"/paired_comparisons/{name}/statistical_evidence/accuracy_delta_pp_ci/{index}", "frozen_question_bootstrap; not_recomputed_from_aggregates")
        for key in ("corrected", "regressed"):
            row("holdout_paired", name, key, outcomes[key], "count", "holdout", f"/paired_comparisons/{name}/paired_outcomes/{key}")
        seed = "1" if name.endswith("20261003") else "2"
        reference = f"A_{seed}" if "_A_" in name else "P"
        paired_table.append([f"$C_{seed}-{reference}$", f"{comparison['accuracy_delta_pp']:+.2f}",
                             f"[{ci[0]:.2f}, {ci[1]:.2f}]", outcomes["corrected"], outcomes["regressed"]])
    table("PublicPairedTable", ["对照", "差值（百分点）", r"95\% 区间", "改正", "退步"], paired_table, "lrrrr")

    primary = report["primary"]
    close(primary["accuracy_delta_pp"], sum(report["paired_comparisons"][f"C_vs_A_{seed}"]["accuracy_delta_pp"] for seed in [20261003, 20261004]) / 2)
    for metric in ["accuracy_delta_pp", "A_mean_accuracy", "C_mean_accuracy"]:
        row("holdout_primary", "mean_two_continuation_seeds", metric, primary[metric], "pp" if metric.endswith("pp") else "fraction", "holdout", f"/primary/{metric}")
    for index, bound in enumerate(primary["accuracy_delta_pp_ci"]):
        row("holdout_primary", "mean_two_continuation_seeds", ["ci_low", "ci_high"][index], bound, "pp",
            "holdout", f"/primary/accuracy_delta_pp_ci/{index}", "frozen_joint_question_bootstrap; not_recomputed_from_aggregates")
    for seed in [20261003, 20261004]:
        a, c, p = (report["arms"][key]["totals"] for key in [f"A_{seed}", f"C_{seed}", "P"])
        for metric in ["total_tokens", "invalid_calls", "generated_tokens"]:
            row("cost_ratios", f"C_vs_A_{seed}", metric + "_change_pct", 100 * (c[metric] / a[metric] - 1), "percent",
                "holdout", f"/arms/C_{seed}/totals/{metric};/arms/A_{seed}/totals/{metric}", "100*(C/A-1)")
        row("cost_ratios", f"C_vs_P_{seed}", "total_tokens_ratio", c["total_tokens"] / p["total_tokens"], "ratio", "holdout",
            f"/arms/C_{seed}/totals/total_tokens;/arms/P/totals/total_tokens", "C/P")

    corpus_table = []
    for arm, metrics in docs["corpus"]["arms"].items():
        close(metrics["supervised_tokens"], docs["corpus"]["budget"]["total"])
        for metric in ["records", "input_tokens", "supervised_tokens", "masked_by_budget"]:
            row("training_corpus", arm, metric, metrics[metric], "count", "corpus", f"/arms/{arm}/{metric}")
        corpus_table.append([arm, f"{metrics['records']:,}", f"{metrics['supervised_tokens']:,}",
                             f"{metrics['input_tokens']:,}", metrics["masked_by_budget"]])
    table("PublicTrainingTable", ["组别", "记录数", "监督 token", "输入 token", "预算追加屏蔽"], corpus_table, "lrrrr")
    for key, value in docs["pairs"]["counts"].items():
        row("recovery_pairs", "construction", key, value, "count", "pairs", f"/counts/{key}")
    for key, value in docs["pairs"]["accepted_divergence_execution"].items():
        row("recovery_pairs", "divergence", key, value, "count", "pairs", f"/accepted_divergence_execution/{key}")
    for metric in ["formal_training_questions", "verified_success_questions", "combined_unique_training_questions"]:
        row("training_corpus", "coverage", metric, docs["corpus"][metric], "count", "corpus", f"/{metric}")
    for section in ["real_recovery_coverage", "ordinary_coverage"]:
        for metric in ["used_unique_questions", "selected_records"]:
            row("training_corpus", section, metric, docs["corpus"][section][metric], "count", "corpus", f"/{section}/{metric}")
    for reuse, count in docs["corpus"]["real_recovery_coverage"]["reuse_histogram"].items():
        row("training_corpus", "pair_reuse", "questions_repeated_" + reuse + "_times", count, "count", "corpus",
            f"/real_recovery_coverage/reuse_histogram/{reuse}")
    for source in ["initial_input", "program_input", "clean_input", "recovery_input", "clean_seed2_input", "recovery_seed2_input"]:
        for metric in ["epochs", "batch_size", "accumulation", "max_length", "learning_rate", "seed"]:
            row("training_setup", source, metric, docs[source]["config"][metric], "configuration", source, f"/config/{metric}")
    for split, data in docs["split"]["splits"].items():
        row("data_split", split, "questions", len(data["ids"]), "count", "split", f"/splits/{split}/ids", "len(ids); metadata only")
    for metric in ["batch_size", "agent_max_calls", "agent_per_turn_generated_tokens", "total_generated_tokens", "max_context", "seed", "python_hash_seed"]:
        row("inference_setup", "fixed_holdout", metric, docs["protocol"]["inference"][metric], "configuration", "protocol", f"/inference/{metric}")

    dev_table = []
    for index, source in enumerate(["dev1", "dev2"], 1):
        d = docs[source]
        for arm, key in [("A", "baseline"), ("C", "candidate")]:
            row("development", f"{arm}_{index}", "correct", d["arms"][key]["correct"], "count", source, f"/arms/{key}/correct")
        ci = d["statistical_evidence"]["accuracy_delta_pp_ci"]
        row("development", f"C_vs_A_{index}", "delta_pp", d["accuracy_delta_pp"], "pp", source, "/accuracy_delta_pp")
        for bound_index, bound in enumerate(ci):
            row("development", f"C_vs_A_{index}", ["ci_low", "ci_high"][bound_index], bound, "pp", source,
                f"/statistical_evidence/accuracy_delta_pp_ci/{bound_index}")
        dev_table.append([index, f"{100*d['arms']['baseline']['accuracy']:.2f}", f"{100*d['arms']['candidate']['accuracy']:.2f}",
                          f"{d['accuracy_delta_pp']:+.2f}", f"[{ci[0]:.2f}, {ci[1]:.2f}]"])
    table("PublicDevTable", ["续训种子", r"A（\%）", r"C（\%）", "差值（百分点）", r"95\% 区间"], dev_table, "lrrrr")

    rl_table = []
    for label, count in docs["rl"]["matched_first_seed_correct_out_of_500"].items():
        row("rl_extension", label, "correct_out_of_500", count, "count", "rl", f"/matched_first_seed_correct_out_of_500/{label}")
    for label in ["B", "D"]:
        for metric in ["optimizer_steps", "question_groups", "rollouts", "unique_training_questions"]:
            row("rl_setup", label, metric, docs["rl_summary"]["training"][label][metric], "count", "rl_summary", f"/training/{label}/{metric}")
    for label in ["B_vs_A", "D_vs_C", "D_vs_B"]:
        d = docs["rl"]["comparisons"][label]
        row("rl_extension", label, "delta_pp", d["delta_pp"], "pp", "rl", f"/comparisons/{label}/delta_pp")
        for index, bound in enumerate(d["ci_pp"]):
            row("rl_extension", label, ["ci_low", "ci_high"][index], bound, "pp", "rl", f"/comparisons/{label}/ci_pp/{index}")
        rl_table.append([label.replace("_vs_", "--"), f"{d['delta_pp']:+.2f}", f"[{d['ci_pp'][0]:.2f}, {d['ci_pp'][1]:.2f}]"])
    table("PublicRLTable", ["对照", "差值（百分点）", r"95\% 区间"], rl_table, "lrr")
    feedback_table = []
    for label, d in docs["feedback"]["diagnostic_results"].items():
        for metric in ["normal_correct", "masked_correct", "delta_pp"]:
            row("feedback_diagnostic", label, metric, d[metric], "pp" if metric.endswith("pp") else "count", "feedback", f"/diagnostic_results/{label}/{metric}")
        for index, bound in enumerate(d["ci_pp"]):
            row("feedback_diagnostic", label, ["ci_low", "ci_high"][index], bound, "pp", "feedback", f"/diagnostic_results/{label}/ci_pp/{index}")
        feedback_table.append([labels[label], d["normal_correct"], d["masked_correct"], f"{d['delta_pp']:+.2f}",
                               f"[{d['ci_pp'][0]:.2f}, {d['ci_pp'][1]:.2f}]"])
    table("PublicFeedbackTable", ["模型", "原始正确数", "屏蔽正确数", "差值（百分点）", r"95\% 区间"], feedback_table, "lrrrr")
    group_names = {"reference_steps_le_5": r"参考步数 $\leq 5$", "reference_steps_gt_5": r"参考步数 $>5$",
                   "qualifier": "限定条件", "set_operation": "集合运算", "comparison_numeric_or_count": "比较、数值或计数"}
    group_table = []
    for label, d in report["descriptive_overlapping_groups"].items():
        row("descriptive_groups", label, "questions", d["questions"], "count", "holdout", f"/descriptive_overlapping_groups/{label}/questions")
        for seed, delta in d["C_minus_A_pp_by_seed"].items():
            row("descriptive_groups", label, f"delta_pp_{seed}", delta, "pp", "holdout", f"/descriptive_overlapping_groups/{label}/C_minus_A_pp_by_seed/{seed}")
        group_table.append([group_names[label], d["questions"], *[f"{d['C_minus_A_pp_by_seed'][str(seed)]:+.2f}" for seed in [20261003, 20261004]]])
    table("PublicGroupTable", ["问题组", "题数", "$C_1-A_1$（百分点）", "$C_2-A_2$（百分点）"], group_table, "lrrr")

    stream = io.StringIO(newline="")
    writer = csv.DictWriter(stream, fieldnames=list(rows[0]), lineterminator="\n")
    writer.writeheader()
    writer.writerows(rows)
    outputs = {"results_tables.csv": stream.getvalue(), "generated_tables.tex": "\n".join(tex) + "\n"}
    sources = {RESULTS + name: {"sha256": digest(ROOT / RESULTS / name), "role": key} for key, name in FILES.items()}
    sources.update({"experiments/agent_feedback/" + name: {"sha256": digest(ROOT / "experiments/agent_feedback" / name), "role": "frozen_implementation"} for name in CODE})
    authored = ["04_execution_feedback_method.tex", "05_public_experiments.tex", "review.tex", "export_evidence.py"]
    manifest = {"version": "thesis_public_evidence_v1", "evidence_cutoff": "2026-10-04",
                "scope": "public aggregate tables and frozen implementation; no raw trajectories, questions, gold, or weights opened by this exporter",
                "sources": sources,
                "outputs_sha256": {**{name: hashlib.sha256(body.encode()).hexdigest() for name, body in outputs.items()},
                                   **{name: digest(OUT / name) for name in authored}},
                "table_rows": len(rows),
                "validation": {"frozen_summary_hash_bindings": True, "aggregate_arithmetic": True,
                               "replay_count": 10000, "replay_mismatches": 0,
                               "bootstrap_intervals": "copied with source hashes; cannot recompute joint-seed bootstrap from marginals",
                               "pdf_compilation": "not_performed; xelatex unavailable in authoring environment"},
                "claim_limits": ["two continuation seeds share an initial adapter", "project holdout is not official hidden test",
                                 "equal supervised token budgets, unequal input tokens and compute", "first divergence need not be a semantic error",
                                 "4 of 418 accepted divergence actions were rejected", "no demonstrated incremental RL benefit in this short trial",
                                 "detailed error-string mechanism not established", "C costs about 24 times P total inference tokens",
                                 "answer equality and replay consistency do not establish condition fidelity", "no new references asserted"]}
    outputs["evidence_manifest.json"] = json.dumps(manifest, ensure_ascii=False, indent=2) + "\n"
    return outputs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = build()
    for name, content in outputs.items():
        artifact = OUT / name
        if args.check:
            if not artifact.is_file() or artifact.read_text() != content:
                raise SystemExit(f"Stale evidence export: {artifact.relative_to(ROOT)}")
        else:
            artifact.write_text(content)
    print(json.dumps({"status": "checked" if args.check else "exported", "outputs": list(outputs)}, ensure_ascii=False))


if __name__ == "__main__":
    main()
